# POETRY CONFIG

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "easyApp"
version = "0.1.0"
description = "The application skeleton in the easy universe."
license = "BSD-3-Clause"
authors = ["Andrew Sazonov", "Simon Ward"]
readme = "README.md"
homepage = "https://github.com/easyScience/easyApp"
documentation = "https://github.com/easyScience/easyApp"
include = ["CHANGELOG.md"]
packages = [ { include = "easyApp" } ]

[tool.poetry.dependencies]
python = '^3.7.0, <3.10'
dicttoxml = "^1.7.4"
requests = "^2.25.1"
PySide6 = '^6.3.1'

[tool.poetry.dev-dependencies]
pytest = "^5.2"

# CUSTOM CONFIG
