# Use hatch to build the application.
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Information about the EasyExampleApp project.
# Note that while the project is called EasyExampleApp
# the application itself is EasyExample.
[tool.poetry]
name = "EasyApp"
version = "0.2.2-beta"
description = "Graphical application skeleton in the EasyScience universe."
authors = ["Andrew Sazonov <andrew.sazonov@ess.eu>"]
license = "BSD-3-Clause"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Development Status :: 4 - Beta"
]
packages = [ { include = "EasyApp" } ]  # Force to use capital letters in the installed EasyApp package

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
PySide6 = ">=6.4.2"
