name: wasm

on:
  push:
  #schedule:
  #  - cron: '*/120 8-18 * * *'  # every 2 hours from 8:00 to 18:00 every day

jobs:
  build: # the first job
    # current job matrix. if modified, remember to UPDATE the strategy in the next job
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    steps: # job steps
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install emsdk
        if: False
        shell: bash
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          git pull
          ./emsdk install 3.1.50		# this version is needed for Qt 6.7
          ./emsdk activate 3.1.50

      - name: Install Qt for WebAssembly
        shell: bash
        run: |
          curl -L -O https://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
          ls -l
          chmod u+x qt-unified-linux-x64-online.run
        #  curl -L -O https://download.qt.io/official_releases/online_installers/qt-unified-linux-arm64-online.run
        #  ./qt-unified-linux-arm64-online.run \
        #  --root /home/runner/Qt \
        #  --accept-licenses \
        #  --accept-obligations \
        #  --default-answer \
        #  --confirm-command \
        #  install qt.qt6.672.wasm_singlethread qt.qt6.672.qt5compat

      - name: Install Qt for WebAssembly
        shell: bash
        run: |
          ./qt-unified-linux-x64-online.run
